### ISSUE TITLE
Ruby 3.1.0 errors with Psych::DisallowedClass: Tried to load unspecified class: Time

### ISSUE THREAD

**Issue by IanVaughan** [facebook/facebook-ruby-business-sdk#161]
### Which SDK version are you using?
`v0.12.0.1`

### What's the issue?
`Psych::DisallowedClass: Tried to load unspecified class: Time`

Need to update Ruby config gem version. as per https://github.com/rubyconfig/config/pull/306

```
/Users/ianvaughan/.asdf/installs/ruby/3.1.0/lib/ruby/3.1.0/psych/class_loader.rb:99:in `find': Tried to load unspecified class: Date (Psych::DisallowedClass)
	from /Users/ianvaughan/.asdf/installs/ruby/3.1.0/lib/ruby/3.1.0/psych/class_loader.rb:28:in `load'
	from (eval):2:in `date'
	from /Users/ianvaughan/.asdf/installs/ruby/3.1.0/lib/ruby/3.1.0/psych/scalar_scanner.rb:59:in `tokenize'
	from /Users/ianvaughan/.asdf/installs/ruby/3.1.0/lib/ruby/3.1.0/psych/visitors/to_ruby.rb:65:in `deserialize'
	from /Users/ianvaughan/.asdf/installs/ruby/3.1.0/lib/ruby/3.1.0/psych/visitors/to_ruby.rb:128:in `visit_Psych_Nodes_Scalar'
	from /Users/ianvaughan/.asdf/installs/ruby/3.1.0/lib/ruby/3.1.0/psych/visitors/visitor.rb:30:in `visit'
	from /Users/ianvaughan/.asdf/installs/ruby/3.1.0/lib/ruby/3.1.0/psych/visitors/visitor.rb:6:in `accept'
	from /Users/ianvaughan/.asdf/installs/ruby/3.1.0/lib/ruby/3.1.0/psych/visitors/to_ruby.rb:35:in `accept'
	from /Users/ianvaughan/.asdf/installs/ruby/3.1.0/lib/ruby/3.1.0/psych/visitors/to_ruby.rb:338:in `block in register_empty'
	from /Users/ianvaughan/.asdf/installs/ruby/3.1.0/lib/ruby/3.1.0/psych/visitors/to_ruby.rb:338:in `each'
	from /Users/ianvaughan/.asdf/installs/ruby/3.1.0/lib/ruby/3.1.0/psych/visitors/to_ruby.rb:338:in `register_empty'
	from /Users/ianvaughan/.asdf/installs/ruby/3.1.0/lib/ruby/3.1.0/psych/visitors/to_ruby.rb:146:in `visit_Psych_Nodes_Sequence'
	from /Users/ianvaughan/.asdf/installs/ruby/3.1.0/lib/ruby/3.1.0/psych/visitors/visitor.rb:30:in `visit'
	from /Users/ianvaughan/.asdf/installs/ruby/3.1.0/lib/ruby/3.1.0/psych/visitors/visitor.rb:6:in `accept'
	from /Users/ianvaughan/.asdf/installs/ruby/3.1.0/lib/ruby/3.1.0/psych/visitors/to_ruby.rb:35:in `accept'
        from /Users/ianvaughan/.asdf/installs/ruby/3.1.0/lib/ruby/3.1.0/psych/visitors/to_ruby.rb:345:in `block in revive_hash'
	from /Users/ianvaughan/.asdf/installs/ruby/3.1.0/lib/ruby/3.1.0/psych/visitors/to_ruby.rb:343:in `each'
	from /Users/ianvaughan/.asdf/installs/ruby/3.1.0/lib/ruby/3.1.0/psych/visitors/to_ruby.rb:343:in `each_slice'
	from /Users/ianvaughan/.asdf/installs/ruby/3.1.0/lib/ruby/3.1.0/psych/visitors/to_ruby.rb:343:in `revive_hash'
	from /Users/ianvaughan/.asdf/installs/ruby/3.1.0/lib/ruby/3.1.0/psych/visitors/to_ruby.rb:167:in `visit_Psych_Nodes_Mapping'
	from /Users/ianvaughan/.asdf/installs/ruby/3.1.0/lib/ruby/3.1.0/psych/visitors/visitor.rb:30:in `visit'
	from /Users/ianvaughan/.asdf/installs/ruby/3.1.0/lib/ruby/3.1.0/psych/visitors/visitor.rb:6:in `accept'
	from /Users/ianvaughan/.asdf/installs/ruby/3.1.0/lib/ruby/3.1.0/psych/visitors/to_ruby.rb:35:in `accept'
	from /Users/ianvaughan/.asdf/installs/ruby/3.1.0/lib/ruby/3.1.0/psych/visitors/to_ruby.rb:318:in `visit_Psych_Nodes_Document'
	from /Users/ianvaughan/.asdf/installs/ruby/3.1.0/lib/ruby/3.1.0/psych/visitors/visitor.rb:30:in `visit'
	from /Users/ianvaughan/.asdf/installs/ruby/3.1.0/lib/ruby/3.1.0/psych/visitors/visitor.rb:6:in `accept'
	from /Users/ianvaughan/.asdf/installs/ruby/3.1.0/lib/ruby/3.1.0/psych/visitors/to_ruby.rb:35:in `accept'
	from /Users/ianvaughan/.asdf/installs/ruby/3.1.0/lib/ruby/3.1.0/psych.rb:335:in `safe_load'
	from /Users/ianvaughan/.asdf/installs/ruby/3.1.0/lib/ruby/3.1.0/psych.rb:370:in `load'
	from /Users/ianvaughan/.asdf/installs/ruby/3.1.0/lib/ruby/3.1.0/psych.rb:671:in `block in load_file'
	from /Users/ianvaughan/.asdf/installs/ruby/3.1.0/lib/ruby/3.1.0/psych.rb:670:in `open'
	from /Users/ianvaughan/.asdf/installs/ruby/3.1.0/lib/ruby/3.1.0/psych.rb:670:in `load_file'
	from /Users/ianvaughan/.asdf/installs/ruby/3.1.0/lib/ruby/gems/3.1.0/gems/business-2.2.1/lib/business/calendar.rb:44:in `block in find_calendar_data'
	from /Users/ianvaughan/.asdf/installs/ruby/3.1.0/lib/ruby/gems/3.1.0/gems/business-2.2.1/lib/business/calendar.rb:38:in `each'
	from /Users/ianvaughan/.asdf/installs/ruby/3.1.0/lib/ruby/gems/3.1.0/gems/business-2.2.1/lib/business/calendar.rb:38:in `detect'
	from /Users/ianvaughan/.asdf/installs/ruby/3.1.0/lib/ruby/gems/3.1.0/gems/business-2.2.1/lib/business/calendar.rb:38:in `find_calendar_data'
	from /Users/ianvaughan/.asdf/installs/ruby/3.1.0/lib/ruby/gems/3.1.0/gems/business-2.2.1/lib/business/calendar.rb:21:in `load'
	from /Users/ianvaughan/outfund/core-app/config/initializers/business.rb:4:in `<main>'
	from /Users/ianvaughan/.asdf/installs/ruby/3.1.0/lib/ruby/gems/3.1.0/gems/bootsnap-1.9.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:60:in `load'
	from /Users/ianvaughan/.asdf/installs/ruby/3.1.0/lib/ruby/gems/3.1.0/gems/bootsnap-1.9.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:60:in `load'
	from /Users/ianvaughan/.asdf/installs/ruby/3.1.0/lib/ruby/gems/3.1.0/gems/activesupport-6.1.4.3/lib/active_support/dependencies.rb:326:in `block in load'
	from /Users/ianvaughan/.asdf/installs/ruby/3.1.0/lib/ruby/gems/3.1.0/gems/activesupport-6.1.4.3/lib/active_support/dependencies.rb:299:in `load_dependency'
	from /Users/ianvaughan/.asdf/installs/ruby/3.1.0/lib/ruby/gems/3.1.0/gems/activesupport-6.1.4.3/lib/active_support/dependencies.rb:326:in `load'
	from /Users/ianvaughan/.asdf/installs/ruby/3.1.0/lib/ruby/gems/3.1.0/gems/railties-6.1.4.3/lib/rails/engine.rb:681:in `block in load_config_initializer'
	from /Users/ianvaughan/.asdf/installs/ruby/3.1.0/lib/ruby/gems/3.1.0/gems/activesupport-6.1.4.3/lib/active_support/notifications.rb:205:in `instrument'
	from /Users/ianvaughan/.asdf/installs/ruby/3.1.0/lib/ruby/gems/3.1.0/gems/railties-6.1.4.3/lib/rails/engine.rb:680:in `load_config_initializer'
	from /Users/ianvaughan/.asdf/installs/ruby/3.1.0/lib/ruby/gems/3.1.0/gems/railties-6.1.4.3/lib/rails/engine.rb:634:in `block (2 levels) in <class:Engine>'
	from /Users/ianvaughan/.asdf/installs/ruby/3.1.0/lib/ruby/gems/3.1.0/gems/railties-6.1.4.3/lib/rails/engine.rb:633:in `each'
	from /Users/ianvaughan/.asdf/installs/ruby/3.1.0/lib/ruby/gems/3.1.0/gems/railties-6.1.4.3/lib/rails/engine.rb:633:in `block in <class:Engine>'
	from /Users/ianvaughan/.asdf/installs/ruby/3.1.0/lib/ruby/gems/3.1.0/gems/railties-6.1.4.3/lib/rails/initializable.rb:32:in `instance_exec'
	from /Users/ianvaughan/.asdf/installs/ruby/3.1.0/lib/ruby/gems/3.1.0/gems/railties-6.1.4.3/lib/rails/initializable.rb:32:in `run'
	from /Users/ianvaughan/.asdf/installs/ruby/3.1.0/lib/ruby/gems/3.1.0/gems/railties-6.1.4.3/lib/rails/initializable.rb:61:in `block in run_initializers'
	from /Users/ianvaughan/.asdf/installs/ruby/3.1.0/lib/ruby/3.1.0/tsort.rb:228:in `block in tsort_each'
	from /Users/ianvaughan/.asdf/installs/ruby/3.1.0/lib/ruby/3.1.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
	from /Users/ianvaughan/.asdf/installs/ruby/3.1.0/lib/ruby/3.1.0/tsort.rb:422:in `block (2 levels) in each_strongly_connected_component_from'
	from /Users/ianvaughan/.asdf/installs/ruby/3.1.0/lib/ruby/3.1.0/tsort.rb:431:in `each_strongly_connected_component_from'
	from /Users/ianvaughan/.asdf/installs/ruby/3.1.0/lib/ruby/3.1.0/tsort.rb:421:in `block in each_strongly_connected_component_from'
	from /Users/ianvaughan/.asdf/installs/ruby/3.1.0/lib/ruby/gems/3.1.0/gems/railties-6.1.4.3/lib/rails/initializable.rb:50:in `each'
	from /Users/ianvaughan/.asdf/installs/ruby/3.1.0/lib/ruby/gems/3.1.0/gems/railties-6.1.4.3/lib/rails/initializable.rb:50:in `tsort_each_child'
	from /Users/ianvaughan/.asdf/installs/ruby/3.1.0/lib/ruby/3.1.0/tsort.rb:415:in `call'
	from /Users/ianvaughan/.asdf/installs/ruby/3.1.0/lib/ruby/3.1.0/tsort.rb:415:in `each_strongly_connected_component_from'
	from /Users/ianvaughan/.asdf/installs/ruby/3.1.0/lib/ruby/3.1.0/tsort.rb:349:in `block in each_strongly_connected_component'
	from /Users/ianvaughan/.asdf/installs/ruby/3.1.0/lib/ruby/3.1.0/tsort.rb:347:in `each'
	from /Users/ianvaughan/.asdf/installs/ruby/3.1.0/lib/ruby/3.1.0/tsort.rb:347:in `call'
	from /Users/ianvaughan/.asdf/installs/ruby/3.1.0/lib/ruby/3.1.0/tsort.rb:347:in `each_strongly_connected_component'
	from /Users/ianvaughan/.asdf/installs/ruby/3.1.0/lib/ruby/3.1.0/tsort.rb:226:in `tsort_each'
	from /Users/ianvaughan/.asdf/installs/ruby/3.1.0/lib/ruby/3.1.0/tsort.rb:205:in `tsort_each'
	from /Users/ianvaughan/.asdf/installs/ruby/3.1.0/lib/ruby/gems/3.1.0/gems/railties-6.1.4.3/lib/rails/initializable.rb:60:in `run_initializers'
	from /Users/ianvaughan/.asdf/installs/ruby/3.1.0/lib/ruby/gems/3.1.0/gems/railties-6.1.4.3/lib/rails/application.rb:391:in `initialize!'
	from /Users/ianvaughan/outfund/core-app/config/environment.rb:5:in `<main>'
	from /Users/ianvaughan/.asdf/installs/ruby/3.1.0/lib/ruby/gems/3.1.0/gems/bootsnap-1.9.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
	from /Users/ianvaughan/.asdf/installs/ruby/3.1.0/lib/ruby/gems/3.1.0/gems/bootsnap-1.9.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
	from /Users/ianvaughan/.asdf/installs/ruby/3.1.0/lib/ruby/gems/3.1.0/gems/bootsnap-1.9.3/lib/bootsnap/load_path_cache/loaded_features_index.rb:100:in `register'
	from /Users/ianvaughan/.asdf/installs/ruby/3.1.0/lib/ruby/gems/3.1.0/gems/bootsnap-1.9.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
	from /Users/ianvaughan/.asdf/installs/ruby/3.1.0/lib/ruby/gems/3.1.0/gems/bootsnap-1.9.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
	from /Users/ianvaughan/.asdf/installs/ruby/3.1.0/lib/ruby/gems/3.1.0/gems/zeitwerk-2.5.2/lib/zeitwerk/kernel.rb:36:in `require'
	from /Users/ianvaughan/.asdf/installs/ruby/3.1.0/lib/ruby/gems/3.1.0/gems/activesupport-6.1.4.3/lib/active_support/dependencies.rb:332:in `block in require'
	from /Users/ianvaughan/.asdf/installs/ruby/3.1.0/lib/ruby/gems/3.1.0/gems/activesupport-6.1.4.3/lib/active_support/dependencies.rb:299:in `load_dependency'
	from /Users/ianvaughan/.asdf/installs/ruby/3.1.0/lib/ruby/gems/3.1.0/gems/activesupport-6.1.4.3/lib/active_support/dependencies.rb:332:in `require'
	from /Users/ianvaughan/.asdf/installs/ruby/3.1.0/lib/ruby/gems/3.1.0/gems/spring-2.1.1/lib/spring/application.rb:106:in `preload'
	from /Users/ianvaughan/.asdf/installs/ruby/3.1.0/lib/ruby/gems/3.1.0/gems/spring-2.1.1/lib/spring/application.rb:157:in `serve'
	from /Users/ianvaughan/.asdf/installs/ruby/3.1.0/lib/ruby/gems/3.1.0/gems/spring-2.1.1/lib/spring/application.rb:145:in `block in run'
	from /Users/ianvaughan/.asdf/installs/ruby/3.1.0/lib/ruby/gems/3.1.0/gems/spring-2.1.1/lib/spring/application.rb:139:in `loop'
	from /Users/ianvaughan/.asdf/installs/ruby/3.1.0/lib/ruby/gems/3.1.0/gems/spring-2.1.1/lib/spring/application.rb:139:in `run'
	from /Users/ianvaughan/.asdf/installs/ruby/3.1.0/lib/ruby/gems/3.1.0/gems/spring-2.1.1/lib/spring/application/boot.rb:19:in `<top (required)>'
	from <internal:/Users/ianvaughan/.asdf/installs/ruby/3.1.0/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
	from <internal:/Users/ianvaughan/.asdf/installs/ruby/3.1.0/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
	from -e:1:in `<main>'
```

**Comment by IanVaughan** [comment]
Version 3.1.1 has now been released https://rubygems.org/gems/config/versions/3.1.1
As per issue here https://github.com/rubyconfig/config/issues/313#issuecomment-1005390643
So this can now be updated and released.

**Comment by alanho** [comment]
closing. issue fixed in external dependency
